team_b = Team("Lazio")
team_b.set_form(3)
team_b.set_head_to_head(3)
team_b.set_absent_players(3)
team_b.set_home_away(3)
team_b.set_standings(3)
team_b.set_rest(3)
team_b.set_motivation(3)
team_b.set_mood(3)