self = Team(data["name"])
self.set_coeff(data["coeff"])
self.set_chance()
self.set_form(data["form"])
self.set_head_to_head(data["head_to_head"])
self.set_absent_players(data["absent_players"])
self.set_standings(data["standings"])
self.set_place(data["place"])
self.set_home_away(data["home_away"])
self.set_rest(data["home_away"])
self.set_motivation(data["motivation"])
self.set_mood(data["mood"])
